// GENERATED FILE - DO NOT EDIT BY HAND.
// Regenerate: pnpm --filter @agent-nexus/cli run gen:id-graph-ledger
//
// THE LEAVES THE ID-THREADING HARNESS CANNOT REACH, AND WHY. A RATCHET.
//
// Each row is a leaf that takes a required id and cannot be swept: either no
// contract binding proves it is a read, or the contract says it mutates.
//
// `id-graph.ledger.test.ts` fails when a leaf appears here that this file does
// not already list. So a NEW command that takes an id and carries no
// `bindCommand` call turns the build red rather than joining a silent backlog -
// which is the whole difference between a harness that holds its coverage and
// one that decays back to nothing over a year.
//
// TO CLEAR A ROW, ADD THE BINDING, then regenerate. Rows LEAVING is always
// fine and never needs an edit here beyond the regeneration.
//
// TO ADD A ROW you must regenerate deliberately, which is the moment to ask
// whether the leaf should simply be bound instead. Adding one is not forbidden;
// it is just not silent.
//
// 🚨 REGENERATING IS NOT A WAY TO CLEAR A RED BUILD. A row that appears because
// somebody landed an unbound read is a coverage regression, and the fix is the
// `bindCommand` call, not this file.

/** `[leaf path, why it cannot be reached]`, sorted by path. */
export const ID_GRAPH_UNCOVERED: readonly (readonly [string, string])[] = [
  ["access-card delete", "unbound-no-provable-method"],
  ["access-card get", "unbound-no-provable-method"],
  ["access-card update", "bound-but-mutates"],
  ["admin vibe-build-job claim", "unbound-no-provable-method"],
  ["admin vibe-build-job fail", "unbound-no-provable-method"],
  ["admin vibe-build-job succeed", "unbound-no-provable-method"],
  ["admin vibe-build-job time-out", "unbound-no-provable-method"],
  ["admin vibe-consumption-cap get", "unbound-no-provable-method"],
  ["admin vibe-consumption-cap set", "unbound-no-provable-method"],
  ["admin vibe-cost-safety get", "unbound-no-provable-method"],
  ["admin vibe-cost-safety set", "unbound-no-provable-method"],
  ["admin vibe-deployment await-approval", "unbound-no-provable-method"],
  ["admin vibe-deployment begin-deploy", "unbound-no-provable-method"],
  ["admin vibe-deployment build-succeeded", "unbound-no-provable-method"],
  ["admin vibe-deployment mark-failed", "unbound-no-provable-method"],
  ["admin vibe-deployment mark-healthy", "unbound-no-provable-method"],
  ["admin vibe-deployment mark-rolled-back", "unbound-no-provable-method"],
  ["admin vibe-tenant-cluster complete-teardown", "unbound-no-provable-method"],
  ["admin vibe-tenant-cluster disable", "unbound-no-provable-method"],
  ["admin vibe-tenant-cluster force-converge", "unbound-no-provable-method"],
  ["admin vibe-tenant-cluster provision", "unbound-no-provable-method"],
  ["agent delete", "unbound-no-provable-method"],
  ["agent duplicate", "unbound-no-provable-method"],
  ["agent generate-profile-picture", "unbound-no-provable-method"],
  ["agent get", "unbound-no-provable-method"],
  ["agent update", "bound-but-mutates"],
  ["agent upload-profile-picture", "unbound-no-provable-method"],
  ["agent-collection attach", "unbound-no-provable-method"],
  ["agent-collection detach", "unbound-no-provable-method"],
  ["agent-eval batch get", "unbound-no-provable-method"],
  ["agent-eval run abort", "unbound-no-provable-method"],
  ["agent-eval run compare", "unbound-no-provable-method"],
  ["agent-eval run delete", "unbound-no-provable-method"],
  ["agent-eval run execute", "unbound-no-provable-method"],
  ["agent-eval run get", "unbound-no-provable-method"],
  ["agent-eval run results", "unbound-no-provable-method"],
  ["agent-eval run transcript", "unbound-no-provable-method"],
  ["agent-eval schedule delete", "unbound-no-provable-method"],
  ["agent-eval schedule pause", "unbound-no-provable-method"],
  ["agent-eval schedule resume", "unbound-no-provable-method"],
  ["agent-eval schedule update", "bound-but-mutates"],
  ["agent-eval template attach", "unbound-no-provable-method"],
  ["agent-eval template clone", "unbound-no-provable-method"],
  ["agent-eval template delete", "unbound-no-provable-method"],
  ["agent-eval template detach", "unbound-no-provable-method"],
  ["agent-eval template get", "unbound-no-provable-method"],
  ["agent-eval template update", "unbound-no-provable-method"],
  ["agent-eval trigger delete", "unbound-no-provable-method"],
  ["agent-eval webhook delete", "unbound-no-provable-method"],
  ["agent-eval webhook get", "unbound-no-provable-method"],
  ["agent-skill add-preset", "unbound-no-provable-method"],
  ["agent-skill create", "bound-but-mutates"],
  ["agent-skill delete", "unbound-no-provable-method"],
  ["agent-skill download", "unbound-no-provable-method"],
  ["agent-skill get", "unbound-no-provable-method"],
  ["agent-skill list", "unbound-no-provable-method"],
  ["agent-skill update", "unbound-no-provable-method"],
  ["agent-skill upload", "unbound-no-provable-method"],
  ["agent-tool attach-collection", "bound-but-mutates"],
  ["agent-tool create", "bound-but-mutates"],
  ["agent-tool delete", "bound-but-mutates"],
  ["agent-tool update", "bound-but-mutates"],
  ["analytics metrics", "bound-but-mutates"],
  ["analytics query", "bound-but-mutates"],
  ["asset delete", "bound-but-mutates"],
  ["asset upload", "bound-but-mutates"],
  ["channel whatsapp-sender get", "unbound-no-provable-method"],
  ["channel whatsapp-template delete", "unbound-no-provable-method"],
  ["channel whatsapp-template get", "unbound-no-provable-method"],
  ["chat resume", "declared-unsweepable"],
  ["chat status", "declared-unsweepable"],
  ["chat stop", "bound-but-mutates"],
  ["cloud-import browse", "requires-an-option-we-cannot-supply"],
  ["cloud-import import", "bound-but-mutates"],
  ["cloud-import search", "requires-an-option-we-cannot-supply"],
  ["collection attach-documents", "bound-but-mutates"],
  ["collection delete", "bound-but-mutates"],
  ["collection query", "bound-but-mutates"],
  ["collection remove-document", "bound-but-mutates"],
  ["collection search", "bound-but-mutates"],
  ["collection update", "bound-but-mutates"],
  ["conversation assign", "unbound-no-provable-method"],
  ["conversation assigned-users", "unbound-no-provable-method"],
  ["conversation close", "unbound-no-provable-method"],
  ["conversation comment", "unbound-no-provable-method"],
  ["conversation comments", "unbound-no-provable-method"],
  ["conversation get-metadata", "unbound-no-provable-method"],
  ["conversation mark-as-read", "unbound-no-provable-method"],
  ["conversation messages", "unbound-no-provable-method"],
  ["conversation send-message", "unbound-no-provable-method"],
  ["conversation send-template", "unbound-no-provable-method"],
  ["conversation update-metadata", "unbound-no-provable-method"],
  ["conversation update-status", "bound-but-mutates"],
  ["conversation update-topic", "unbound-no-provable-method"],
  ["credential connect-status", "unbound-no-provable-method"],
  ["credential delete", "unbound-no-provable-method"],
  ["credential get", "unbound-no-provable-method"],
  ["credential update", "unbound-no-provable-method"],
  ["custom-model delete", "bound-but-mutates"],
  ["custom-model update", "bound-but-mutates"],
  ["customer delete", "bound-but-mutates"],
  ["customer note", "bound-but-mutates"],
  ["customer update", "bound-but-mutates"],
  ["deployment delete", "unbound-no-provable-method"],
  ["deployment duplicate", "unbound-no-provable-method"],
  ["deployment embed-config", "unbound-no-provable-method"],
  ["deployment embed-config-update", "bound-but-mutates"],
  ["deployment folder delete", "unbound-no-provable-method"],
  ["deployment folder update", "unbound-no-provable-method"],
  ["deployment get", "unbound-no-provable-method"],
  ["deployment stats", "unbound-no-provable-method"],
  ["deployment template attach", "bound-but-mutates"],
  ["deployment template detach", "unbound-no-provable-method"],
  ["deployment template list", "unbound-no-provable-method"],
  ["deployment template settings", "unbound-no-provable-method"],
  ["deployment template update", "unbound-no-provable-method"],
  ["deployment update", "bound-but-mutates"],
  ["document children", "unbound-no-provable-method"],
  ["document delete", "unbound-no-provable-method"],
  ["document download", "unbound-no-provable-method"],
  ["document get", "unbound-no-provable-method"],
  ["document preview", "unbound-no-provable-method"],
  ["document reprocess", "unbound-no-provable-method"],
  ["document update", "unbound-no-provable-method"],
  ["document upload", "unbound-no-provable-method"],
  ["emulator scenario delete", "bound-but-mutates"],
  ["emulator scenario replay", "unbound-no-provable-method"],
  ["emulator session create", "bound-but-mutates"],
  ["emulator session delete", "bound-but-mutates"],
  ["emulator session get", "unbound-no-provable-method"],
  ["execution cancel", "bound-but-mutates"],
  ["execution diagnose", "declared-unsweepable"],
  ["execution export", "bound-but-mutates"],
  ["execution follow", "unbound-no-provable-method"],
  ["execution retry", "bound-but-mutates"],
  ["external-tool delete", "bound-but-mutates"],
  ["external-tool execute", "unbound-no-provable-method"],
  ["external-tool test", "bound-but-mutates"],
  ["external-tool test-auth", "unbound-no-provable-method"],
  ["external-tool update", "bound-but-mutates"],
  ["external-tool update-auth", "unbound-no-provable-method"],
  ["external-tool update-spec", "unbound-no-provable-method"],
  ["external-tool upload-icon", "bound-but-mutates"],
  ["folder delete", "bound-but-mutates"],
  ["folder update", "bound-but-mutates"],
  ["html-template delete", "unbound-no-provable-method"],
  ["html-template fill", "unbound-no-provable-method"],
  ["html-template render", "unbound-no-provable-method"],
  ["html-template update", "unbound-no-provable-method"],
  ["known-issues", "positional-not-a-path-param"],
  ["mcp tools get", "unbound-no-provable-method"],
  ["phone-number get", "unbound-no-provable-method"],
  ["phone-number release", "unbound-no-provable-method"],
  ["prompt-assistant await-thread", "unbound-no-provable-method"],
  ["prompt-assistant delete-thread", "unbound-no-provable-method"],
  ["prompt-assistant get-thread", "unbound-no-provable-method"],
  ["role add-board", "bound-but-mutates"],
  ["role add-member", "bound-but-mutates"],
  ["role add-permission-set-member", "unbound-no-provable-method"],
  ["role add-responsibility", "unbound-no-provable-method"],
  ["role attach", "bound-but-mutates"],
  ["role collection-grants", "unbound-no-provable-method"],
  ["role coverage", "unbound-no-provable-method"],
  ["role create-permission-set", "bound-but-mutates"],
  ["role creation-request", "unbound-no-provable-method"],
  ["role delete", "unbound-no-provable-method"],
  ["role delete-job-type", "unbound-no-provable-method"],
  ["role delete-permission-set", "unbound-no-provable-method"],
  ["role deletion-request", "unbound-no-provable-method"],
  ["role detach", "bound-but-mutates"],
  ["role get", "unbound-no-provable-method"],
  ["role grant-collection", "unbound-no-provable-method"],
  ["role grant-workspace", "unbound-no-provable-method"],
  ["role members", "unbound-no-provable-method"],
  ["role move-card", "bound-but-mutates"],
  ["role pause", "unbound-no-provable-method"],
  ["role permission-sets", "unbound-no-provable-method"],
  ["role remove-board", "bound-but-mutates"],
  ["role remove-member", "unbound-no-provable-method"],
  ["role remove-permission-set-member", "unbound-no-provable-method"],
  ["role remove-responsibility", "unbound-no-provable-method"],
  ["role reorder-boards", "bound-but-mutates"],
  ["role request-access", "bound-but-mutates"],
  ["role responsibilities", "unbound-no-provable-method"],
  ["role resume", "unbound-no-provable-method"],
  ["role review-access", "bound-but-mutates"],
  ["role review-creation-request", "bound-but-mutates"],
  ["role review-deletion-request", "bound-but-mutates"],
  ["role revoke-collection", "unbound-no-provable-method"],
  ["role revoke-workspace", "unbound-no-provable-method"],
  ["role scope-lines", "unbound-no-provable-method"],
  ["role set-scope-lines", "unbound-no-provable-method"],
  ["role set-system-policy", "unbound-no-provable-method"],
  ["role set-task-duties", "unbound-no-provable-method"],
  ["role set-tasks", "unbound-no-provable-method"],
  ["role set-variables", "unbound-no-provable-method"],
  ["role set-working-year", "unbound-no-provable-method"],
  ["role system-policy", "unbound-no-provable-method"],
  ["role systems", "unbound-no-provable-method"],
  ["role task-duties", "unbound-no-provable-method"],
  ["role tasks", "unbound-no-provable-method"],
  ["role update", "unbound-no-provable-method"],
  ["role update-board", "bound-but-mutates"],
  ["role update-job-type", "bound-but-mutates"],
  ["role update-permission-set", "bound-but-mutates"],
  ["role variables", "unbound-no-provable-method"],
  ["role working-year", "unbound-no-provable-method"],
  ["role workspace-grants", "unbound-no-provable-method"],
  ["skill-folder delete", "bound-but-mutates"],
  ["skill-folder update", "bound-but-mutates"],
  ["task delete", "unbound-no-provable-method"],
  ["task duplicate", "bound-but-mutates"],
  ["task execute", "bound-but-mutates"],
  ["task get", "unbound-no-provable-method"],
  ["task update", "bound-but-mutates"],
  ["task-eval dataset add", "unbound-no-provable-method"],
  ["task-eval dataset list", "unbound-no-provable-method"],
  ["task-eval execute", "unbound-no-provable-method"],
  ["task-eval judge", "unbound-no-provable-method"],
  ["task-eval results", "unbound-no-provable-method"],
  ["task-eval session create", "bound-but-mutates"],
  ["task-eval session delete", "unbound-no-provable-method"],
  ["task-eval session get", "unbound-no-provable-method"],
  ["template delete", "unbound-no-provable-method"],
  ["template folder delete", "unbound-no-provable-method"],
  ["template folder update", "unbound-no-provable-method"],
  ["template generate", "unbound-no-provable-method"],
  ["template get", "unbound-no-provable-method"],
  ["template upload", "unbound-no-provable-method"],
  ["ticket attach", "unbound-no-provable-method"],
  ["ticket attachments", "unbound-no-provable-method"],
  ["ticket close", "unbound-no-provable-method"],
  ["ticket comment", "unbound-no-provable-method"],
  ["ticket comments", "unbound-no-provable-method"],
  ["ticket get", "unbound-no-provable-method"],
  ["ticket update", "bound-but-mutates"],
  ["tool connection-status", "unbound-no-provable-method"],
  ["tool create-credential", "unbound-no-provable-method"],
  ["tool credentials", "unbound-no-provable-method"],
  ["tool delete-credential", "unbound-no-provable-method"],
  ["tool execute", "unbound-no-provable-method"],
  ["tool get", "unbound-no-provable-method"],
  ["tool resolve-options", "unbound-no-provable-method"],
  ["tool test", "unbound-no-provable-method"],
  ["tracing delete", "unbound-no-provable-method"],
  ["tracing export", "bound-but-mutates"],
  ["tracing generation", "unbound-no-provable-method"],
  ["tracing trace", "unbound-no-provable-method"],
  ["tracks agent beat", "bound-but-mutates"],
  ["tracks agent close", "bound-but-mutates"],
  ["tracks agent open", "bound-but-mutates"],
  ["tracks archive", "bound-but-mutates"],
  ["tracks current-step", "bound-but-mutates"],
  ["tracks diary append", "bound-but-mutates"],
  ["tracks event append", "bound-but-mutates"],
  ["tracks memory delete", "bound-but-mutates"],
  ["tracks memory put", "bound-but-mutates"],
  ["tracks plan import", "bound-but-mutates"],
  ["tracks section create", "bound-but-mutates"],
  ["tracks section rename", "bound-but-mutates"],
  ["tracks set-next-owner", "bound-but-mutates"],
  ["tracks set-status", "bound-but-mutates"],
  ["tracks task claim", "bound-but-mutates"],
  ["tracks task edge", "bound-but-mutates"],
  ["tracks task toggle", "bound-but-mutates"],
  ["tracks task why-not-ready", "unbound-no-provable-method"],
  ["user-group add-member", "bound-but-mutates"],
  ["user-group delete", "bound-but-mutates"],
  ["user-group remove-member", "bound-but-mutates"],
  ["user-group update", "bound-but-mutates"],
  ["version create", "unbound-no-provable-method"],
  ["version delete", "unbound-no-provable-method"],
  ["version get", "unbound-no-provable-method"],
  ["version publish", "unbound-no-provable-method"],
  ["version restore", "unbound-no-provable-method"],
  ["version update", "unbound-no-provable-method"],
  ["vibe app attach-repo", "unbound-no-provable-method"],
  ["vibe app create", "unbound-no-provable-method"],
  ["vibe app delete", "unbound-no-provable-method"],
  ["vibe app edge-token", "unbound-no-provable-method"],
  ["vibe app get", "unbound-no-provable-method"],
  ["vibe app logs", "unbound-no-provable-method"],
  ["vibe app provision-repo", "unbound-no-provable-method"],
  ["vibe app register-as-tool", "bound-but-mutates"],
  ["vibe app reprovision-repo", "unbound-no-provable-method"],
  ["vibe app rotate-edge-token", "unbound-no-provable-method"],
  ["vibe app update", "unbound-no-provable-method"],
  ["vibe app visibility", "unbound-no-provable-method"],
  ["vibe approvals decide", "unbound-no-provable-method"],
  ["vibe approvals get", "unbound-no-provable-method"],
  ["vibe deploy", "unbound-no-provable-method"],
  ["vibe deploy-state", "unbound-no-provable-method"],
  ["vibe deployments get", "unbound-no-provable-method"],
  ["vibe deployments list", "unbound-no-provable-method"],
  ["vibe env list", "unbound-no-provable-method"],
  ["vibe env rm", "unbound-no-provable-method"],
  ["vibe env set", "unbound-no-provable-method"],
  ["vibe git-project clone", "unbound-no-provable-method"],
  ["vibe git-project create", "unbound-no-provable-method"],
  ["vibe git-project delete", "unbound-no-provable-method"],
  ["vibe git-project get", "unbound-no-provable-method"],
  ["vibe git-project pull", "unbound-no-provable-method"],
  ["vibe git-project reprovision", "unbound-no-provable-method"],
  ["vibe rollback", "unbound-no-provable-method"],
  ["workflow batch", "bound-but-mutates"],
  ["workflow branch create", "unbound-no-provable-method"],
  ["workflow branch delete", "unbound-no-provable-method"],
  ["workflow branch list", "unbound-no-provable-method"],
  ["workflow branch update", "unbound-no-provable-method"],
  ["workflow delete", "unbound-no-provable-method"],
  ["workflow duplicate", "unbound-no-provable-method"],
  ["workflow edge create", "bound-but-mutates"],
  ["workflow edge delete", "unbound-no-provable-method"],
  ["workflow get", "unbound-no-provable-method"],
  ["workflow layout", "unbound-no-provable-method"],
  ["workflow node create", "unbound-no-provable-method"],
  ["workflow node delete", "unbound-no-provable-method"],
  ["workflow node get", "unbound-no-provable-method"],
  ["workflow node output-format", "unbound-no-provable-method"],
  ["workflow node reload-props", "unbound-no-provable-method"],
  ["workflow node test", "unbound-no-provable-method"],
  ["workflow node test-payload", "unbound-no-provable-method"],
  ["workflow node update", "unbound-no-provable-method"],
  ["workflow node variables", "unbound-no-provable-method"],
  ["workflow node-type", "unbound-no-provable-method"],
  ["workflow overview", "unbound-no-provable-method"],
  ["workflow publish", "unbound-no-provable-method"],
  ["workflow test", "unbound-no-provable-method"],
  ["workflow test-node", "unbound-no-provable-method"],
  ["workflow trigger", "bound-but-mutates"],
  ["workflow unpublish", "unbound-no-provable-method"],
  ["workflow update", "unbound-no-provable-method"],
  ["workflow upload-icon", "unbound-no-provable-method"],
  ["workflow validate", "unbound-no-provable-method"],
  ["workspace create", "bound-but-mutates"],
  ["workspace delete", "bound-but-mutates"],
  ["workspace rename", "bound-but-mutates"],
  ["workspace restore", "bound-but-mutates"],
  ["workspace search", "declared-unsweepable"]
];
