/**
 * The registry format this package WRITES must be readable by the skill bundle
 * this same package SHIPS.
 *
 * `~/.nexus-mcp/workspace-mounts.json` is not a private file. `nexus claude-code
 * install` writes the `nexus-workspaces` skill and its hook scripts onto the
 * user's machine (`src/commands/claude-code.ts` → `SKILLS`), and those parse the
 * registry directly — a jq path-resolver, a jq WebDAV base-URL lookup, and
 * several Python liveness/firewall probes.
 *
 * NEX-2360 rekeyed the file to `<kind>:<id>|<slug>`. A reader that indexes that
 * object by BARE SLUG gets nothing back, and nothing is what these readers are
 * worst at:
 *   - `ws_path` falls through to its in-sandbox default `/mnt/workspace/<slug>`,
 *     a path that does not exist on a local machine, so an agent reads and
 *     writes the WRONG directory with no error anywhere;
 *   - the WebDAV recipe builds `null/api/dav/…` and every upload 404s.
 *
 * The bundle resolves the new keys correctly today: every reader scans the
 * registry's VALUES and matches on each record's own `slug`, scoped to the acting
 * org. This file exists to keep it that way, because the coupling is the kind
 * nobody looks for — an audit of the registry's WRITERS finds only
 * `mount-registry.ts` and concludes no migration is needed, while the readers that
 * would break ship from a different repository entirely.
 *
 * ── Why this cannot be fixed in this repository ──────────────────────────────
 *
 * `src/skills-content.generated.ts` is generated by `scripts/bundle-skills.ts`
 * from `NexusGPT/claude-code-skills-nexus` at the SHA in `skills-nexus.lock`,
 * and `scripts/postinstall.sh` runs `gen:skills` ON EVERY INSTALL INCLUDING CI.
 * A hand-edit here is overwritten by the next install; it is a build artifact,
 * not a source file. Closing this needs the readers fixed upstream and the lock
 * bumped — two repositories, one landing order.
 *
 * ── How this test behaves ───────────────────────────────────────────────────
 *
 * It fails while the CLI writes composite keys AND any bundled reader resolves by
 * bare slug, and it names every offending site. It retires itself if the key
 * format is ever reverted (`CLI_WRITES_COMPOSITE_KEYS`), rather than leaving a
 * stale red behind. It is deliberately NOT a characterisation test of a broken
 * state — a green suite over a broken shipped reader is the failure mode it
 * exists to prevent, which is why both arms carry their own negative controls
 * and the check ships a `--self-test`.
 *
 * ── What the scan covers, and the one thing it skips ────────────────────────
 *
 * `scripts/bundle-skills.ts` collects the upstream tree with NO extension
 * allowlist (deliberately — an allowlist there once silently dropped every
 * non-.md/.ts asset a skill told an agent to read). So skills-nexus's own Python
 * test harness ships too: `hooks/test_inprocdb.py`, `test_reactev.py` and
 * `test_tankhome.py` are in today's bundle, and the fix for this very coupling
 * adds `hooks/test_mountreg.py`.
 *
 * A test suite ABOUT a broken reader necessarily contains the broken reader's
 * text — fixture registries in the old shape, a docstring naming the jq path it
 * mutation-tests against. A literal scan cannot tell that from the reader
 * itself, so `test_mountreg.py` alone tripped three of these needles while every
 * live reader was already fixed. That is a false positive of the pure kind: the
 * evidence for the fix reads as the bug.
 *
 * The scan therefore skips `test_*.py` IN THE HOOKS BUNDLE, and ONLY that. The
 * question this file asks is "does anything that will EXECUTE against a user's
 * registry index it by bare slug", and a `test_*.py` in the hooks tree does not
 * execute there: nothing in the installed `settings.json` routes a hook event to
 * it, and the installer writes it as inert text.
 *
 * That argument is about hooks/ specifically and does not generalise, so neither
 * does the exclusion. It was originally written as a bare path pattern applied to
 * the WHOLE bundle, which would have dropped an executable helper named
 * `test_*.py` under any skill directory — and skill directories do carry runnable
 * Python that a SKILL.md tells an agent to invoke (`shared/scripts/fastpack.py`).
 * Such a file would have shipped, been runnable, and gone unscanned. The
 * predicate is now scoped to the bundle whose justification covers it, and
 * `keeps every executable registry reader inside the scan` below pins both the
 * narrowness and the bundle.
 *
 * SKIPPED FROM THE SCAN, NOT FROM THE BUNDLE — and the difference is a real
 * open question, not an oversight. Shipping an upstream repo's test harness into
 * every user's `.claude/hooks/` is hard to justify on its own merits. But that is
 * a change to `collectFiles()`, i.e. to what `nexus claude-code install` writes
 * to disk, with a blast radius across every skill asset and every doc that
 * references one — a different change, needing its own review, not a rider on a
 * cross-repo compatibility fix. Filed as such rather than done quietly here.
 *
 * HOW THIS CHECKS, AND WHY IT CHANGED. It was a list of broken spellings asserted
 * absent from the bundle, with `.get(slug)` deliberately RECEIVER-BLIND so that a
 * respelling which dropped the receiver could not dodge it. The bet was that "any
 * literal occurrence in the bundle is a reader, with no case to argue".
 *
 * The bet is false, and a correct file paid for it. `hooks/lib/automount.py` reads
 * `rows.get(slug)` where `rows = _rows_for(scope, mounts)` — a dict built by scanning
 * `mounts.values()`, keyed on each record's own `slug`, and admitted only for the
 * acting scope. The receiver is an org-scoped local, not the registry; the key format
 * cannot reach it. The scan accused a reader that reads correctly, and the remedy it
 * printed — "scan the registry's VALUES and match on the record's own slug field" —
 * was already implemented in the accused file. A gate whose prescribed remedy is
 * unwritable has misidentified the site.
 *
 * The answer was not to exempt the file, nor to rename the local until the needle went
 * quiet: both leave a detector that cannot tell `registry.get(slug)` from
 * `scoped.get(slug)`, so the next correct reader pays again. The detector was repaired
 * at its input instead. `scripts/registry-reader-contract.py` now DRIVES each resolver
 * against fixture registries and PARSES the rest with python3's `ast`, so the receiver
 * is part of the question. Its header owns the property, both arms, and the coverage it
 * does not claim.
 */
import { spawnSync } from "node:child_process";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { mountKey } from "./mount-registry";
import {
  getAgentFiles,
  getClaudeMd,
  getHookFiles,
  getSettingsJson,
  getSharedFiles,
  getSkills,
  type SkillFile
} from "./skills-content.generated";

/**
 * Does this CLI still write bare-slug registry keys? Derived from `mountKey`
 * itself rather than hardcoded, so reverting the key format retires this test
 * automatically instead of leaving a stale red behind.
 */
const CLI_WRITES_COMPOSITE_KEYS =
  mountKey({ orgId: "org_probe", baseUrl: "https://example.invalid" }, "general-context") !==
  "general-context";

interface ContractReport {
  sha: string;
  armA: {
    coverage: string[];
    results: {
      resolver: string;
      case: string;
      ok: boolean;
      want: unknown;
      got: unknown;
      detail: string;
    }[];
    failures: number;
  };
  armB: {
    scanned: string[];
    violations: { file: string; line: number; receiver: string; op: string; function: string }[];
    unparsed: string[];
  };
  ok: boolean;
}

const BUNDLE_PATH = path.join(__dirname, "skills-content.generated.json");

/**
 * EVERY surface `nexus claude-code install` writes to the user's machine, not
 * just the skill markdown — `util/skills-install.ts` installs six of them, and
 * the Python registry parsers live in `HOOK_FILES`, which a `SKILLS`-only scan
 * misses entirely. The bundle a reader ships in has no bearing on whether it
 * breaks, so the scan follows the installer's list rather than the obvious one.
 */
function installedSurfaces(): { bundle: string; file: SkillFile }[] {
  const surfaces: { bundle: string; file: SkillFile }[] = [];
  for (const [slug, entry] of Object.entries(getSkills())) {
    for (const file of entry.files) surfaces.push({ bundle: slug, file });
  }
  for (const [bundle, files] of [
    ["shared", getSharedFiles()],
    ["hooks", getHookFiles()],
    ["agents", getAgentFiles()]
  ] as const) {
    for (const file of files) surfaces.push({ bundle, file });
  }
  surfaces.push({ bundle: "root", file: { path: "CLAUDE.md", content: getClaudeMd() } });
  surfaces.push({ bundle: "root", file: { path: "settings.json", content: getSettingsJson() } });
  return surfaces;
}

/** The bundle skills-nexus's Python harness lives in — and the only one it may hide in. */
const HARNESS_BUNDLE = "hooks";

/**
 * skills-nexus's own Python test harness, which the unfiltered bundler ships
 * alongside the hooks. Anchored to a path SEGMENT so it cannot match a skill
 * document that merely happens to contain the substring, restricted to `.py` —
 * the only tests in that repo, and the only file type whose fixtures are literal
 * registry snippets — and now restricted to the `hooks` BUNDLE as well.
 *
 * The bundle scoping is the third of those anchors and the one that was missing.
 * The argument for the exclusion is specific to hooks/: nothing in the installed
 * `settings.json` routes a hook event to a `test_*.py` there, so the installer
 * writes it as inert text. That argument does not travel. A skill directory is
 * not a hook registry — its files are read and RUN because a SKILL.md tells an
 * agent to run them (`skills/shared/scripts/fastpack.py` is exactly that), so an
 * executable helper named `test_something.py` under any skill would have been
 * dropped from the scan while still shipping and still being runnable. The
 * predicate is now as narrow as its justification: hooks bundle, path segment,
 * `.py`.
 */
function isUpstreamTestHarness(bundle: string, filePath: string): boolean {
  return bundle === HARNESS_BUNDLE && /(^|\/)test_[^/]*\.py$/.test(filePath);
}

/** The installed surfaces that can actually run against a user's registry. */
function scannedSurfaces(): { bundle: string; file: SkillFile }[] {
  return installedSurfaces().filter((s) => !isUpstreamTestHarness(s.bundle, s.file.path));
}

/**
 * The contract check is a PROGRAM, not a pattern, and it lives beside this file at
 * `scripts/registry-reader-contract.py`. Read its header for the property it answers
 * and for what it deliberately does not cover.
 *
 * This used to be a list of broken spellings asserted absent from the bundle. That
 * detector reported `hooks/lib/automount.py` for `rows.get(slug)`, where `rows` is
 * `_rows_for(scope, mounts)` — a dict built by scanning `mounts.values()` and matching
 * each record's own `slug`, admitted only for the acting scope. The receiver was an
 * org-scoped local, never the registry, and the remedy the failure prescribed was
 * already implemented in the file it accused. A receiver-blind substring cannot tell
 * `registry.get(slug)` from `scoped.get(slug)`; so the check now asks the receiver.
 */
function runContractCheck(args: string[]): { code: number; stdout: string; stderr: string } {
  const script = path.join(__dirname, "..", "scripts", "registry-reader-contract.py");
  const run = spawnSync("python3", [script, ...args], {
    encoding: "utf-8",
    maxBuffer: 64 * 1024 * 1024
  });
  // FAIL CLOSED. A missing interpreter is not a pass: skipping here would retire the
  // whole property on any runner that happens not to carry python3, and the skip would
  // read as green. The runner image installs it (deployment/ci-runner/Dockerfile) and
  // ubuntu-latest carries it, so an absence here is a real regression to surface.
  if (run.error || run.status === null) {
    throw new Error(
      `registry-reader-contract.py could not be run (${String(run.error)}). ` +
        "python3 is required for this check — it is NOT optional, and this test refuses " +
        "to pass by skipping. Install python3 on the runner."
    );
  }
  return { code: run.status, stdout: run.stdout ?? "", stderr: run.stderr ?? "" };
}

describe("the bundled skills read the mount registry the way this CLI writes it", () => {
  it("scans the shipped bundle rather than vacuously passing over an empty one", () => {
    // The control for the control. If the bundle ever arrives empty — a
    // generator change, a bad tarball, an import that resolves to a stub — the
    // scan below finds nothing and reports the coupling as closed. An empty set
    // satisfies "no bare-slug readers" perfectly, and that is the one way this
    // file could go green while the breakage ships.
    const surfaces = installedSurfaces();
    expect(Object.keys(getSkills()).length).toBeGreaterThan(0);
    expect(surfaces.length).toBeGreaterThan(0);
    // Both halves that matter: the markdown runbook and the Python hooks. A
    // regression that dropped HOOK_FILES from the scan is invisible otherwise —
    // it was the first version of this spec's own bug.
    expect(getHookFiles().length).toBeGreaterThan(0);
    expect(
      surfaces.filter((s) => s.file.content.includes("workspace-mounts.json")).length
    ).toBeGreaterThan(1);
  });

  it("keeps every executable registry reader inside the scan", () => {
    // The narrowing above is the only thing standing between this tripwire and
    // the class of regression it exists to catch, so it gets asserted rather
    // than trusted. A predicate that grew — to `*.py`, to `hooks/`, to anything
    // with "test" in the name — would leave a file that still says
    // "ships no bare-slug reader" while scanning less and less.
    const scanned = new Set(scannedSurfaces().map((s) => `${s.bundle}/${s.file.path}`));
    for (const reader of [
      "hooks/lib/hook_core.py", // mount_record / mount_path / dav_slug_if_mounted
      "hooks/nexus-awareness.py", // _probe_mount, _gc_ident, the AW4 boundary block
      "hooks/nexus-pretool.py", // _tools_index_path, dav_when_mounted, BND1
      "nexus-workspaces/SKILL.md", // ws_mount / ws_path + the bulk-PUT recipe
      "root/CLAUDE.md" // the boundary-check schema line
    ]) {
      expect(scanned, `${reader} must stay in the scan`).toContain(reader);
    }

    const installed = installedSurfaces();
    const excluded = installed.filter((s) => !scanned.has(`${s.bundle}/${s.file.path}`));
    // Everything dropped is a `test_*.py`, and it is a rounding error of the
    // bundle. Both halves matter: the first says the predicate is the one
    // documented above, the second catches a predicate that still matches only
    // test files but suddenly matches hundreds of them.
    expect(
      excluded.map((s) => `${s.bundle}/${s.file.path}`).filter((p) => !/test_/.test(p))
    ).toEqual([]);
    expect(excluded.every((s) => isUpstreamTestHarness(s.bundle, s.file.path))).toBe(true);
    expect(excluded.length).toBeLessThan(installed.length * 0.05);

    // …and every exclusion is in the ONE bundle whose justification covers it.
    // A `test_*.py` anywhere else is a file a SKILL.md can tell an agent to run
    // (`shared/scripts/fastpack.py` is the existing proof that skill bundles carry
    // executable Python), so it must be scanned like any other reader.
    expect(excluded.map((s) => s.bundle).filter((b) => b !== HARNESS_BUNDLE)).toEqual([]);
    expect(isUpstreamTestHarness("shared", "scripts/test_helper.py")).toBe(false);
    expect(isUpstreamTestHarness("nexus-workspaces", "scripts/test_probe.py")).toBe(false);
    expect(isUpstreamTestHarness(HARNESS_BUNDLE, "test_mountreg.py")).toBe(true);
  });

  it("proves the contract check itself can fail", () => {
    // The check is only worth reading if it has been seen to fail. Its own self-test
    // scores it against synthetic readers that are genuinely broken AND against correct
    // ones — including the exact shape the old substring scan false-positived on, a
    // slug-keyed read whose receiver is a scoped local rather than the registry.
    const run = runContractCheck(["--self-test"]);
    expect(run.stdout + run.stderr).toContain("self-test");
    expect(
      run.code,
      `the contract check's self-test did not pass:\n${run.stdout}\n${run.stderr}`
    ).toBe(0);
  });

  it.skipIf(!CLI_WRITES_COMPOSITE_KEYS)(
    "every bundled reader resolves a mount from composite keys, and stays org-scoped",
    () => {
      const run = runContractCheck([BUNDLE_PATH, "--json"]);
      let report: ContractReport;
      try {
        report = JSON.parse(run.stdout) as ContractReport;
      } catch {
        throw new Error(
          `registry-reader-contract.py did not emit JSON (exit ${run.code}):\n` +
            `${run.stdout}\n${run.stderr}`
        );
      }

      // ── vacuity controls, asserted before the verdict ───────────────────────
      // A run that drove nothing and scanned nothing reports no failures and no
      // violations, which is indistinguishable from a clean bundle. These two say the
      // check had something to judge.
      expect(
        report.armA.coverage.length,
        "ARM A drove NO resolver — a bundle whose resolvers all vanished would otherwise " +
          "report clean. This is the empty-denominator case, not a pass."
      ).toBeGreaterThan(0);
      expect(
        report.armB.scanned.length,
        "ARM B parsed NO file that reads the registry — same empty denominator."
      ).toBeGreaterThan(0);
      // The canonical resolver every hook delegates to must be among what was driven.
      expect(report.armA.coverage).toContain("hook_core.mount_record");
      // A file the parser choked on is neither clean nor dirty; it is unread.
      expect(report.armB.unparsed, "a reader that could not be parsed is not a pass").toEqual([]);

      // ── ARM A: behaviour ───────────────────────────────────────────────────
      const behaviour = report.armA.results.filter((r) => !r.ok);
      expect(
        behaviour.map(
          (r) =>
            `${r.resolver} / ${r.case}: want ${JSON.stringify(r.want)}, ` +
            `got ${JSON.stringify(r.got)} — ${r.detail}`
        ),
        "A bundled reader answered a fixture registry wrongly. `composite-resolves` failing " +
          "means it cannot read the keys this CLI writes; `foreign-org-refused` or " +
          "`anonymous-refused` failing means it hands out another tenant's row."
      ).toEqual([]);

      // ── ARM B: reach ───────────────────────────────────────────────────────
      expect(
        report.armB.violations.map(
          (v) => `${v.file}:${v.line} ${v.receiver}${v.op} in ${v.function}()`
        ),
        "A registry-derived value is read by BARE SLUG. Against the composite keys this " +
          "CLI writes it resolves nothing, and the failure mode is a wrong path or a null " +
          "base URL rather than an error. Scan the registry's VALUES and match on the " +
          "record's own `slug` field, scoped to the acting org."
      ).toEqual([]);

      expect(report.ok, `contract check REFUSED:\n${run.stdout}`).toBe(true);
    }
  );
});
