/**
 * The registry format this package WRITES must be readable by the skill bundle
 * this same package SHIPS.
 *
 * `~/.nexus-mcp/workspace-mounts.json` is not a private file. `nexus claude-code
 * install` writes the `nexus-workspaces` skill and its hook scripts onto the
 * user's machine (`src/commands/claude-code.ts` → `SKILLS`), and those parse the
 * registry directly — a jq path-resolver, a jq WebDAV base-URL lookup, and
 * several Python liveness/firewall probes. Every one of them indexes the JSON
 * object by BARE SLUG.
 *
 * NEX-2360 rekeys the file to `<kind>:<id>|<slug>`. A bare-slug index into that
 * object returns nothing, and nothing is what these readers are worst at:
 *   - `ws_path` falls through to its in-sandbox default `/mnt/workspace/<slug>`,
 *     a path that does not exist on a local machine, so an agent reads and
 *     writes the WRONG directory with no error anywhere;
 *   - the WebDAV recipe builds `null/api/dav/…` and every upload 404s.
 *
 * That is a shipped reader broken by a format change inside the very package
 * that ships it, which is precisely the coupling nobody looks for: an audit of
 * the registry's WRITERS finds only `workspace-mounts.ts` and concludes no
 * migration is needed. So the coupling gets a test instead of a comment.
 *
 * ── Why this cannot be fixed in this repository ──────────────────────────────
 *
 * `src/skills-content.generated.ts` is generated by `scripts/bundle-skills.ts`
 * from `NexusGPT/claude-code-skills-nexus` at the SHA in `skills-nexus.lock`,
 * and `scripts/postinstall.sh` runs `gen:skills` ON EVERY INSTALL INCLUDING CI.
 * A hand-edit here is overwritten by the next install; it is a build artifact,
 * not a source file. Closing this needs the readers fixed upstream and the lock
 * bumped — two repositories, one landing order.
 *
 * ── How this test behaves ───────────────────────────────────────────────────
 *
 * It fails while the CLI writes composite keys AND the bundle still reads bare
 * slugs, and it names every offending site. It greens by itself the moment
 * either half moves: fix the skills repo and bump the lock, or revert the key
 * format. It is deliberately NOT a characterisation test of the broken state —
 * a green suite over a broken shipped reader is the failure mode it exists to
 * prevent.
 *
 * ── What the scan covers, and the one thing it skips ────────────────────────
 *
 * `scripts/bundle-skills.ts` collects the upstream tree with NO extension
 * allowlist (deliberately — an allowlist there once silently dropped every
 * non-.md/.ts asset a skill told an agent to read). So skills-nexus's own Python
 * test harness ships too: `hooks/test_inprocdb.py`, `test_reactev.py` and
 * `test_tankhome.py` are in today's bundle, and the fix for this very coupling
 * adds `hooks/test_mountreg.py`.
 *
 * A test suite ABOUT a broken reader necessarily contains the broken reader's
 * text — fixture registries in the old shape, a docstring naming the jq path it
 * mutation-tests against. A literal scan cannot tell that from the reader
 * itself, so `test_mountreg.py` alone tripped three of these needles while every
 * live reader was already fixed. That is a false positive of the pure kind: the
 * evidence for the fix reads as the bug.
 *
 * The scan therefore skips `test_*.py` IN THE HOOKS BUNDLE, and ONLY that. The
 * question this file asks is "does anything that will EXECUTE against a user's
 * registry index it by bare slug", and a `test_*.py` in the hooks tree does not
 * execute there: nothing in the installed `settings.json` routes a hook event to
 * it, and the installer writes it as inert text.
 *
 * That argument is about hooks/ specifically and does not generalise, so neither
 * does the exclusion. It was originally written as a bare path pattern applied to
 * the WHOLE bundle, which would have dropped an executable helper named
 * `test_*.py` under any skill directory — and skill directories do carry runnable
 * Python that a SKILL.md tells an agent to invoke (`shared/scripts/fastpack.py`).
 * Such a file would have shipped, been runnable, and gone unscanned. The
 * predicate is now scoped to the bundle whose justification covers it, and
 * `keeps every executable registry reader inside the scan` below pins both the
 * narrowness and the bundle.
 *
 * SKIPPED FROM THE SCAN, NOT FROM THE BUNDLE — and the difference is a real
 * open question, not an oversight. Shipping an upstream repo's test harness into
 * every user's `.claude/hooks/` is hard to justify on its own merits. But that is
 * a change to `collectFiles()`, i.e. to what `nexus claude-code install` writes
 * to disk, with a blast radius across every skill asset and every doc that
 * references one — a different change, needing its own review, not a rider on a
 * cross-repo compatibility fix. Filed as such rather than done quietly here.
 *
 * The upstream fix ALSO stops quoting the broken shapes where prose can just
 * describe them (NexusGPT/claude-code-skills-nexus#23), so the two halves are
 * independent: neither alone is load-bearing, and a regression has to defeat
 * both to reach a user. That is now a stated convention on both sides —
 * DESCRIBE, NEVER SPELL, with no exemption for a NEVER-warning and none for a
 * respelling that dodges a needle. See `BARE_SLUG_READERS` for why the exemption
 * was refused and what the needle list does instead.
 */
import { describe, expect, it } from "vitest";

import {
  getAgentFiles,
  getClaudeMd,
  getHookFiles,
  getSettingsJson,
  getSharedFiles,
  getSkills,
  type SkillFile
} from "./skills-content.generated";
import { mountKey } from "./workspace-mounts";

/**
 * Does this CLI still write bare-slug registry keys? Derived from `mountKey`
 * itself rather than hardcoded, so reverting the key format retires this test
 * automatically instead of leaving a stale red behind.
 */
const CLI_WRITES_COMPOSITE_KEYS =
  mountKey({ orgId: "org_probe", baseUrl: "https://example.invalid" }, "general-context") !==
  "general-context";

interface BareSlugReader {
  /** The exact text that ships, so a match is a fact and not an interpretation. */
  needle: string;
  /** What it does, and what it does INSTEAD once the keys change. */
  what: string;
}

/**
 * Literal substrings, not patterns. A regex over 7.5 MB of skill markdown
 * false-positives on prose that merely discusses the registry; a literal that
 * appears in the shipped text either is the reader or is not. Each disappears
 * when the upstream skill is fixed, so the list needs no maintenance here.
 *
 * ── DESCRIBE, NEVER SPELL, and why there is no warning exemption ────────────
 *
 * The literal scan has an obvious hole: an author can satisfy it by RESPELLING
 * the construct just far enough to miss a needle — the same jq path with the
 * brackets moved, the same dict lookup with the receiver dropped — while the
 * broken form still ships. Round 2 of skills-nexus#23 closed a finding exactly
 * that way, writing the bulk-PUT recipe's bare-slug lookup as an equivalent jq
 * spelling inside a NEVER warning, and hook_core.py's failure-mode comment did
 * the same to the Python one. The needle went quiet; the text did not change.
 *
 * Two ways out, and they are exclusive. Either quoting the anti-pattern inside a
 * warning is legitimate and the scan learns to ignore warning lines, or the
 * shipped text never spells the construct at all. This picks the SECOND, for
 * both repos:
 *
 *   - a warning exemption is the dodge with a rubber stamp. The scan would have
 *     to decide "is this line a warning" by heuristic over 7.5 MB of markdown
 *     and Python comments, and any editor who can write the word NEVER above a
 *     line can then silence a REAL regression the same way. The check would be
 *     weakest exactly where the text is most confident;
 *   - describing costs nothing. Every one of these constructs reads fine in
 *     words — "a top-level lookup under the bare slug" — and skills-nexus was
 *     already doing that in hook_core.py's registry preamble and test_mountreg's
 *     header before this. Making it the rule rather than a habit is what lets
 *     the scan stay literal AND stay sound: any literal occurrence in the bundle
 *     is a reader, with no case to argue.
 *
 * So the broken form is spelled in exactly ONE place — here, the detector, which
 * is a test file and does not ship. Everything downstream describes it. The
 * needles below therefore include the KNOWN RESPELLINGS of each construct, so
 * the round-2 dodge is red rather than green: `.[$s]` and `.["<slug>"]` catch
 * the jq path however its brackets are arranged, and `.get(slug)` catches the
 * Python lookup with the receiver dropped. A needle that is a strict prefix of
 * another is not redundant — it is the generalisation, and the longer one stays
 * for the message it carries.
 */
const BARE_SLUG_READERS: BareSlugReader[] = [
  {
    needle: ".[$s].mountPath",
    what:
      "`ws_path()` — the R#43 path resolver every workspace-touching skill routes its file " +
      "access through. Returns empty on a composite key, so it falls back to the in-sandbox " +
      "default `/mnt/workspace/<slug>` and the agent operates on a path that does not exist locally."
  },
  {
    needle: ".[$s]",
    what:
      "the same `ws_path()` jq path with its brackets rearranged — `.[$s] | .mountPath` and " +
      "`.[$s].mountPath` are one program. The generalisation of the needle above; a respelling " +
      "must not be a way to go green."
  },
  {
    needle: '."<slug>".baseUrl',
    what:
      "the bulk WebDAV upload recipe's `BASE=$(jq -r …)`. Returns null on a composite key, " +
      "so every PUT targets `null/api/dav/<slug>/…`."
  },
  {
    needle: '.["<slug>"]',
    what:
      "the bracket spelling of that same bulk-PUT lookup. Round 2 of skills-nexus#23 closed " +
      "the finding above by rewriting the path this way inside a NEVER warning — the needle " +
      "went quiet and the construct stayed. Describe it in words instead."
  },
  {
    needle: "mounts.get(slug)",
    what: "`_probe_mount` — the hook's mount-liveness probe; a composite key reads as unmounted."
  },
  {
    needle: ".get(slug)",
    what:
      "the same Python lookup with the receiver dropped, which is how hook_core.py's " +
      "failure-mode comment respelled it. Generalises the needle above."
  },
  {
    needle: '.get(slug, {}).get("mountPath")',
    what:
      "`dav_slug_if_mounted` — the guard that redirects hand-rolled WebDAV writes to the mount; " +
      "silently stops firing."
  },
  {
    needle: 'mounts.get("general-context")',
    what: "hook lookups of the general-context mount, keyed by bare slug."
  },
  {
    needle: 'mounts.get("tools")',
    what: "hook lookup of the tools mount, keyed by bare slug."
  },
  {
    needle: '"<slug>": {',
    what:
      "the documented registry schema in the `## Discovery` section — it tells the reader the " +
      "top-level keys ARE slugs, which is what the parsers above implement."
  },
  {
    needle: "the registry keys on bare slug",
    what:
      'the "One live mount per slug per machine" runbook. NEX-2360 makes this false: the key ' +
      "records the acting org, and NEX-2372 records mode and org on the record."
  },
  {
    needle: "Parallel same-slug mounts across orgs are not possible",
    what:
      "false as of NEX-2360 — that is the feature. Agents following this unmount and remount " +
      "every slug on each profile switch for no reason."
  },
  {
    needle: "The registry records NEITHER mode NOR org",
    what: "false as of NEX-2372 — `readOnly`, `orgId`, `orgName` and `profile` are all recorded."
  }
];

interface Hit {
  needle: string;
  what: string;
  bundle: string;
  file: string;
}

/**
 * EVERY surface `nexus claude-code install` writes to the user's machine, not
 * just the skill markdown — `util/skills-install.ts` installs six of them, and
 * the Python registry parsers live in `HOOK_FILES`, which a `SKILLS`-only scan
 * misses entirely. The bundle a reader ships in has no bearing on whether it
 * breaks, so the scan follows the installer's list rather than the obvious one.
 */
function installedSurfaces(): { bundle: string; file: SkillFile }[] {
  const surfaces: { bundle: string; file: SkillFile }[] = [];
  for (const [slug, entry] of Object.entries(getSkills())) {
    for (const file of entry.files) surfaces.push({ bundle: slug, file });
  }
  for (const [bundle, files] of [
    ["shared", getSharedFiles()],
    ["hooks", getHookFiles()],
    ["agents", getAgentFiles()]
  ] as const) {
    for (const file of files) surfaces.push({ bundle, file });
  }
  surfaces.push({ bundle: "root", file: { path: "CLAUDE.md", content: getClaudeMd() } });
  surfaces.push({ bundle: "root", file: { path: "settings.json", content: getSettingsJson() } });
  return surfaces;
}

/** The bundle skills-nexus's Python harness lives in — and the only one it may hide in. */
const HARNESS_BUNDLE = "hooks";

/**
 * skills-nexus's own Python test harness, which the unfiltered bundler ships
 * alongside the hooks. Anchored to a path SEGMENT so it cannot match a skill
 * document that merely happens to contain the substring, restricted to `.py` —
 * the only tests in that repo, and the only file type whose fixtures are literal
 * registry snippets — and now restricted to the `hooks` BUNDLE as well.
 *
 * The bundle scoping is the third of those anchors and the one that was missing.
 * The argument for the exclusion is specific to hooks/: nothing in the installed
 * `settings.json` routes a hook event to a `test_*.py` there, so the installer
 * writes it as inert text. That argument does not travel. A skill directory is
 * not a hook registry — its files are read and RUN because a SKILL.md tells an
 * agent to run them (`skills/shared/scripts/fastpack.py` is exactly that), so an
 * executable helper named `test_something.py` under any skill would have been
 * dropped from the scan while still shipping and still being runnable. The
 * predicate is now as narrow as its justification: hooks bundle, path segment,
 * `.py`.
 */
function isUpstreamTestHarness(bundle: string, filePath: string): boolean {
  return bundle === HARNESS_BUNDLE && /(^|\/)test_[^/]*\.py$/.test(filePath);
}

/** The installed surfaces that can actually run against a user's registry. */
function scannedSurfaces(): { bundle: string; file: SkillFile }[] {
  return installedSurfaces().filter((s) => !isUpstreamTestHarness(s.bundle, s.file.path));
}

function findBareSlugReaders(): Hit[] {
  const hits: Hit[] = [];
  for (const { bundle, file } of scannedSurfaces()) {
    for (const reader of BARE_SLUG_READERS) {
      if (file.content.includes(reader.needle)) {
        hits.push({ needle: reader.needle, what: reader.what, bundle, file: file.path });
      }
    }
  }
  return hits;
}

describe("the bundled skills read the mount registry the way this CLI writes it", () => {
  it("scans the shipped bundle rather than vacuously passing over an empty one", () => {
    // The control for the control. If the bundle ever arrives empty — a
    // generator change, a bad tarball, an import that resolves to a stub — the
    // scan below finds nothing and reports the coupling as closed. An empty set
    // satisfies "no bare-slug readers" perfectly, and that is the one way this
    // file could go green while the breakage ships.
    const surfaces = installedSurfaces();
    expect(Object.keys(getSkills()).length).toBeGreaterThan(0);
    expect(surfaces.length).toBeGreaterThan(0);
    // Both halves that matter: the markdown runbook and the Python hooks. A
    // regression that dropped HOOK_FILES from the scan is invisible otherwise —
    // it was the first version of this spec's own bug.
    expect(getHookFiles().length).toBeGreaterThan(0);
    expect(
      surfaces.filter((s) => s.file.content.includes("workspace-mounts.json")).length
    ).toBeGreaterThan(1);
  });

  it("keeps every executable registry reader inside the scan", () => {
    // The narrowing above is the only thing standing between this tripwire and
    // the class of regression it exists to catch, so it gets asserted rather
    // than trusted. A predicate that grew — to `*.py`, to `hooks/`, to anything
    // with "test" in the name — would leave a file that still says
    // "ships no bare-slug reader" while scanning less and less.
    const scanned = new Set(scannedSurfaces().map((s) => `${s.bundle}/${s.file.path}`));
    for (const reader of [
      "hooks/lib/hook_core.py", // mount_record / mount_path / dav_slug_if_mounted
      "hooks/nexus-awareness.py", // _probe_mount, _gc_ident, the AW4 boundary block
      "hooks/nexus-pretool.py", // _tools_index_path, dav_when_mounted, BND1
      "nexus-workspaces/SKILL.md", // ws_mount / ws_path + the bulk-PUT recipe
      "root/CLAUDE.md" // the boundary-check schema line
    ]) {
      expect(scanned, `${reader} must stay in the scan`).toContain(reader);
    }

    const installed = installedSurfaces();
    const excluded = installed.filter((s) => !scanned.has(`${s.bundle}/${s.file.path}`));
    // Everything dropped is a `test_*.py`, and it is a rounding error of the
    // bundle. Both halves matter: the first says the predicate is the one
    // documented above, the second catches a predicate that still matches only
    // test files but suddenly matches hundreds of them.
    expect(
      excluded.map((s) => `${s.bundle}/${s.file.path}`).filter((p) => !/test_/.test(p))
    ).toEqual([]);
    expect(excluded.every((s) => isUpstreamTestHarness(s.bundle, s.file.path))).toBe(true);
    expect(excluded.length).toBeLessThan(installed.length * 0.05);

    // …and every exclusion is in the ONE bundle whose justification covers it.
    // A `test_*.py` anywhere else is a file a SKILL.md can tell an agent to run
    // (`shared/scripts/fastpack.py` is the existing proof that skill bundles carry
    // executable Python), so it must be scanned like any other reader.
    expect(excluded.map((s) => s.bundle).filter((b) => b !== HARNESS_BUNDLE)).toEqual([]);
    expect(isUpstreamTestHarness("shared", "scripts/test_helper.py")).toBe(false);
    expect(isUpstreamTestHarness("nexus-workspaces", "scripts/test_probe.py")).toBe(false);
    expect(isUpstreamTestHarness(HARNESS_BUNDLE, "test_mountreg.py")).toBe(true);
  });

  it.skipIf(!CLI_WRITES_COMPOSITE_KEYS)(
    "ships no bare-slug reader of workspace-mounts.json",
    () => {
      const hits = findBareSlugReaders();
      const report = hits
        .map((h) => `  • ${h.bundle}/${h.file}\n      reads: ${h.needle}\n      ${h.what}`)
        .join("\n");

      expect(
        hits,
        hits.length === 0
          ? ""
          : [
              "",
              "The CLI now writes `<kind>:<id>|<slug>` registry keys, but the skill bundle it",
              "installs still indexes ~/.nexus-mcp/workspace-mounts.json by bare slug:",
              "",
              report,
              "",
              "These run on the USER's machine after `nexus claude-code install`. Against a",
              "rekeyed registry they resolve nothing — and their failure mode is a wrong path or",
              "a null base URL, not an error.",
              "",
              "This file is a build artifact: scripts/bundle-skills.ts regenerates it from",
              "NexusGPT/claude-code-skills-nexus at the SHA in packages/cli/skills-nexus.lock, and",
              "scripts/postinstall.sh runs that on every install including CI. Editing it here does",
              "not fix anything. To close this:",
              "  1. in claude-code-skills-nexus, make each reader scan the registry's VALUES and",
              "     match on the record's own `slug` field (with the acting org where it matters)",
              "     instead of indexing by top-level key, and correct the `## Discovery` schema and",
              "     the three one-mount-per-slug claims in the runbook;",
              "  2. bump packages/cli/skills-nexus.lock to that SHA and run `pnpm gen:skills`;",
              "  3. land the two together — the CLI must not publish a key format its own bundled",
              "     skill cannot read.",
              ""
            ].join("\n")
      ).toEqual([]);
    }
  );
});
