#!/usr/bin/env tsx
/**
 * Publish this CLI's route id inventory into the backend, so a `route:` Linear
 * label naming a command that does not exist can be REPORTED instead of filed
 * under a key nobody ever asks for.
 *
 *   pnpm generate:cli-route-inventory        (from the repository root)
 *
 * ── WHAT THIS CLOSES ─────────────────────────────────────────────────────────
 *
 * A known issue reaches a customer only through a `route:<id>` label. Three ways
 * that label can reach nobody, and the first two are already reported by
 * `list-published-known-issues.linear.adapter.ts`:
 *
 *   1. no label at all, or a bare `route:`
 *   2. a label the known-issues read end's schema refuses (`route:agent_list`)
 *   3. `route:agent.lst` — well-formed, schema-clean, and no such command
 *
 * The third is invisible from the backend alone: the set of real route ids is
 * `allRouteIds()`, here, and `apps/backend` does not depend on this package —
 * nor should it, for one string array. This artifact IS that dependency, in the
 * form the repository already uses for one: committed, and regenerated by a gate
 * (`Generated config`, plus the post-merge `generated drift` detector).
 *
 * ── 🚨 THE INVENTORY IS ADVISORY. NOTHING IS EVER DROPPED FOR BEING ABSENT ────
 *
 * It is a snapshot of this tree at the time the backend was built, and a
 * customer runs whatever version of `@agent-nexus/cli` npm gave them. So
 * "absent" means "no caller running that CLI would ask for it", never "no caller
 * can". Making it a publication decision would recreate trigger 1 — a curated
 * issue silently reaching nobody — for every command added after the backend
 * shipped. A stale inventory can only ever cost a spurious warning in a log.
 * `apps/backend/src/known-issues/domain/value-objects/route-inventory.ts` states
 * the same rule at the point of use, and a spec asserts the issue still ships.
 *
 * ── WHY `allRouteIds`, AND NOT A PROJECTION OF THE COMMAND UNIVERSE ──────────
 *
 * `allRouteIds()` is the same derivation `routeIdOf()` performs at runtime when
 * the CLI asks the API about the command it just ran. Taking `CommandNode.path`
 * and swapping its spaces for dots would produce the same strings today and
 * would be a SECOND spelling of one fact — which is the drift this whole defect
 * class is made of.
 *
 * The tree is rebuilt from the root registrars rather than imported from
 * `src/index.ts`, which ends in `program.parseAsync(process.argv)` and would run
 * the CLI against this script's own argv. `command-universe.ts` owns that
 * reasoning; `deriveCommandModules()` makes the same choice for the same reason.
 *
 * ── WHY THE CONTRACT IS IMPORTED BY SOURCE PATH ──────────────────────────────
 *
 * Same reason `v1-contract-projection.ts` does it: `@nexus/types/public-api-v1`
 * resolves to `dist/` under the `node` condition, so importing it that way makes
 * this generator depend on another package's build and read a stale schema when
 * that build is behind. It is the same object either way, which is what keeps
 * the refusal below honest.
 */

import { writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { Command } from "commander";

import { ZPublicApiV1 } from "../../types/src/api/public/v1/index";
import { discoverRootRegistrars } from "../src/command-universe";
import { allRouteIds } from "../src/util/route-id";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");

const OUTPUT = join(
  REPO_ROOT,
  "apps/backend/src/known-issues/domain/value-objects/cli-route-ids.generated.ts"
);

/**
 * A floor, not a target.
 *
 * It exists so a walk that HALF works is a failure rather than a very small
 * inventory — a drop to single digits means a registrar stopped being
 * discovered, not that the CLI shrank. The gate compares byte for byte, so the
 * real count never has to be written down anywhere and cannot go stale here.
 */
const MINIMUM_PLAUSIBLE_ROUTES = 50;

/** The whole CLI tree, rebuilt from its root registrars. */
async function deriveRouteIds(): Promise<string[]> {
  const program = new Command();
  program.name("nexus").exitOverride();

  for (const registrar of await discoverRootRegistrars()) {
    registrar.register(program);
  }

  // Sorted rather than in declaration order: the artifact is diffed by a gate,
  // and a stable order means a new command shows up as one added line instead of
  // a reshuffle nobody can read.
  return [...new Set(allRouteIds(program))].sort();
}

function render(routeIds: readonly string[]): string {
  return `// GENERATED FILE — DO NOT EDIT.
//
// Source: packages/cli/scripts/generate-route-inventory.ts, from the commander
// tree in packages/cli. Regenerate from the repository root with:
//
//     pnpm generate:cli-route-inventory
//
// 🚨 AN OBSERVABILITY INPUT, NEVER A PUBLICATION DECISION. This is a snapshot of
// the CLI this backend was built alongside, and a customer runs whatever version
// npm gave them. Absence from this list means "no caller running that CLI would
// ask for this id" — never "no caller can". Dropping a known issue because its
// route id is missing here would silently lose every issue curated against a
// command added after this backend shipped, which is the exact defect the
// known-issues surface exists to prevent. \`route-inventory.ts\` is the only
// consumer, and it reports; it never filters.

export const CLI_ROUTE_IDS: readonly string[] = [
${routeIds.map((id) => `  ${JSON.stringify(id)}`).join(",\n")}
];
`;
}

async function main(): Promise<void> {
  const routeIds = await deriveRouteIds();

  if (routeIds.length < MINIMUM_PLAUSIBLE_ROUTES) {
    console.error(
      `REFUSED: the tree walk produced ${routeIds.length} route id(s), below the floor of ` +
        `${MINIMUM_PLAUSIBLE_ROUTES}. That is a broken walk, not a small CLI.`
    );
    console.error(
      "  Writing it would turn every `route:` label in the workspace into a " +
        "'no such command' warning."
    );
    process.exit(1);
  }

  // Every id this CLI can produce must be a value the known-issues read end
  // accepts, or the command it names can never carry a `route:` label at all.
  // That is a curation hole with no owner, so it is refused HERE — where someone
  // is adding the command — rather than found later as an inventory entry
  // nothing can ever match.
  const unlabellable = routeIds.filter(
    (id) => !ZPublicApiV1.KnownIssuesForRoute.Params.safeParse({ route: id }).success
  );
  if (unlabellable.length > 0) {
    console.error(
      `REFUSED: ${unlabellable.length} command(s) have a route id the known-issues read end ` +
        "cannot accept, so no `route:` label could ever reach them:"
    );
    for (const id of unlabellable) console.error(`    ${id}`);
    console.error(
      "  Rename the command to dot-separated lowercase, or widen " +
        "KnownIssuesForRouteParamsSchema in packages/types."
    );
    process.exit(1);
  }

  writeFileSync(OUTPUT, render(routeIds), "utf8");
  console.log(`✓ ${routeIds.length} route id(s) written to ${relative(REPO_ROOT, OUTPUT)}`);
}

void main();
